# Generated by Django 3.1.4 on 2020-12-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
