# Generated by Django 3.1.4 on 2020-12-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20201219_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
